[project]
name = "dagster-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.11.13",
    "dagster-webserver>=1.11.13",
    "duckdb>=1.4.1",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pytest>=8.4.2",
]
